[package]
name = "avn-service"
version = "0.7.0"
authors = ["Aventus Network Services Team"]
edition = "2018"
license = "GPL-3.0"
homepage = "http://www.aventus.io/"
repository = "https://github.com/Aventus-Network-Services/avn-tier2/"

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0" }
structopt = "0.3.8"
log = "0.4.8"
serde_json = "1.0"
serde = "1.0"
tide = { version = "0.16.0"}
web3 = { version = "0.15.0", default-features = false, features = ["http-tls"]} # implies tls feature

# This version must be compatible with web3
tokio = { version = "0.2.25", features = ["full"] }

hex = "0.4"
libsecp256k1 = { version = "0.3.5", default-features = false, features = ["hmac"]}
ethereum-tx-sign = { version = "3.0.5", git = "https://github.com/Aventus-Network-Services/ethereum-tx-sign.git", branch = "v3.0.5" }
# This needs to be the same version as the one used in web3, parity-scale-codec and ethereum-transactions pallet
ethereum-types = "0.11.0"

node-primitives = { version = "2.0.0", git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }
node-runtime = { version = "2.0.0", path = "../../runtime" }
node-rpc = { version = "2.0.0", path = "../../rpc" }

# primitives
sp-core = { version = "3.0.0", git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }
sp-runtime = { version = "3.0.0", git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }
sp-avn-common = { version = "0.7.0", default-features = false, path = "../../../../primitives/avn-common" }
sp-keystore = { version = "0.9.0", git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }

# client dependencies
sc-keystore = { version = "3.0.0", git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }
sc-service = { version = "0.9.0", default-features = false, git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }
sc-client-api = { version = "3.0.0", git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }

frame-system = { version = "3.0.0", git = "https://github.com/Aventus-Network-Services/substrate.git", branch = "v3.0.0_avn" }