{
 "title": "Substrate Testnet",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Peers", "type": "text", "gridPos": { "h": 1, "w": 7, "x": 0, "y": 0 }, "content": "\n\n\n\n" },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "target": "txcount", "type": "timeseries" },
    { "target": "txcount", "type": "timeseries" },
    { "target": "txcount", "type": "timeseries" },
    { "target": "txcount", "type": "timeseries" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "cpu", "type": "timeseries" },
    { "target": "cpu", "type": "timeseries" },
    { "target": "cpu", "type": "timeseries" },
    { "target": "cpu", "type": "timeseries" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    { "target": "peers", "type": "timeseries" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    { "target": "peers", "type": "timeseries" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "targets": [
    { "target": "peers", "type": "timeseries" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "targets": [
    { "target": "peers", "type": "timeseries" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "target": "memory", "type": "timeseries" },
    { "target": "memory", "type": "timeseries" },
    { "target": "memory", "type": "timeseries" },
    { "target": "memory", "type": "timeseries" }
   ]
  },
  {
   "title": "Bandwidth (Download)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    { "target": "bandwidth_download", "type": "timeseries" },
    { "target": "bandwidth_download", "type": "timeseries" },
    { "target": "bandwidth_download", "type": "timeseries" },
    { "target": "bandwidth_download", "type": "timeseries" }
   ]
  },
  {
   "title": "Bandwidth (Upload)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    { "target": "bandwidth_upload", "type": "timeseries" },
    { "target": "bandwidth_upload", "type": "timeseries" },
    { "target": "bandwidth_upload", "type": "timeseries" },
    { "target": "bandwidth_upload", "type": "timeseries" }
   ]
  }
 ]
}