{
 "title": "Bootstrap Data",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Connected Nodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total{direction=\"in\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total{direction=\"out\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}